# Generated by Django 4.2.3 on 2023-07-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand_chart', '0002_rename_color_optionsaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenthandchart',
            old_name='hl',
            new_name='hj',
        ),
    ]
