# Generated by Django 4.2.3 on 2023-07-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_chart', '0003_rename_hl_contenthandchart_hj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenthandchart',
            name='hj',
            field=models.ManyToManyField(blank=True, related_name='hj_color', to='hand_chart.optionsaction', verbose_name='Позиция HJ'),
        ),
    ]
